ARG PYTHON_IMAGE=python:__PYTHON_VERSION__-bookworm
ARG AGENT_TEMPLATE=__AGENT_TEMPLATE__
FROM ${PYTHON_IMAGE} AS python_runtime

FROM docker.io/docker/sandbox-templates:${AGENT_TEMPLATE}
USER root
COPY --from=python_runtime /usr/local/ /opt/python/
ENV PATH="/opt/python/bin:${PATH}"
USER agent
RUN python --version && python -m venv --help >/dev/null
